#define TICK_TIME 100000
#define SENSOR_QUEUE_NAME   "/sensor_queue"
#define ACTUATOR_QUEUE_NAME "/actuator_queue"
#define REFERENCE_QUEUE_NAME "/reference_queue"
#define WDOG_QUEUE_NAME "/watchdog_queue"
#define QUEUE_PERMISSIONS 0660
#define MAX_MESSAGES 1000
#define MAX_MSG_SIZE 16
#define BUF_SIZE 5